# Generated by Django 5.2.14 on 2026-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='reponsavel_tarefa',
            field=models.CharField(default='nao_atribuido', max_length=255),
        ),
    ]
