# Generated by Django 5.2.14 on 2026-09-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefas_reponsavel_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
