# Generated by Django 5.2.14 on 2026-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefas_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='observacoes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
