# Generated by Django 5.2.14 on 2026-08-31 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='ativo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='validade_fim',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='validade_inicio',
        ),
        migrations.AddField(
            model_name='certificado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='expiry_alert_last_threshold',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Último limiar de dias (30/14/7/…) para o qual o alerta de vencimento foi enviado.', null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Nome do arquivo sem o trecho {senha ...}.', max_length=255),
        ),
        migrations.AddField(
            model_name='certificado',
            name='pfx_encrypted',
            field=models.BinaryField(default=b'temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='senha_encrypted',
            field=models.BinaryField(default=b'temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='certificado',
            name='subject_cn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
