# Generated by Django 5.2.14 on 2026-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_certificado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regime',
            field=models.CharField(default='Simples Nacional', max_length=255),
            preserve_default=False,
        ),
    ]
