# Generated by Django 5.2.14 on 2026-09-04 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
