# Generated by Django 5.2.14 on 2026-09-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_data_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='regime',
            field=models.CharField(choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO REAL', 'Lucro Real'), ('MEI', 'MEI'), ('OUTROS', 'OUTROS')], default='MEI', max_length=40),
        ),
    ]
