# Generated by Django 5.2.14 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='regime',
            field=models.CharField(choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real'), ('MEI', 'MEI'), ('OUTROS', 'Outros')], default='MEI', max_length=40),
        ),
    ]
