# Generated by Django 5.2.14 on 2026-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('ENCARREGADO', 'Encarregado'), ('USUARIO', 'Usuário')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
